- hosts: all, localhost
  become: yes
  vars:
    audio:
      source: EasyEffects Source
      sink: EasyEffects Sink
    # for vfio-pcie
    vfio_pci_ids:
      - '1002:731f' # Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5700 / 5700 XT]
      - '1002:ab38' # Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 HDMI Audio
    # for passthrough
    pci_device_ids:
      # Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5700 / 5700 XT]
      - domain: '0000'
        bus: '03'
        slot: '00'
        function: '0'
        fix_reset_method: yes
      # Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 HDMI Audio
      - domain: '0000'
        bus: '03'
        slot: '00'
        function: '1'
      # ASMedia Technology Inc. ASM2142/ASM3142 USB 3.1 Host Controller
      - domain: '0000'
        bus: '07'
        slot: '00'
        function: '0'
    usb_device_ids: []
    keyboards:
      - '/dev/input/by-path/platform-i8042-serio-0-event-kbd'
    mice: []
  roles:
    - win10
