- name: regenerate linux initramfs
  command: /usr/bin/mkinitcpio -p linux

- name: reload systemd services
  systemd:
    daemon_reload: yes

- name: restart libvirtd.service
  systemd:
    name: libvirtd.service
    enabled: no
    state: restarted

- name: restart virtlogd.socket
  service:
    name: virtlogd.socket
    enabled: yes
    state: restarted

- name: restart persistent-evdev
  systemd:
    name: persistent-evdev.service
    enabled: yes
    state: restarted