- name: regenerate linux initramfs
  command: /usr/bin/mkinitcpio -p linux

- name: restart libvirtd.service
  systemd:
    name: libvirtd.service
    enabled: no
    state: restarted

- name: restart virtlogd.socket
  service:
    name: virtlogd.socket
    enabled: yes
    state: restarted
